#menggunakan docker-compose untuk mempermudah dalam menjalankan aplikasi

# dokcer compose version 3.8
version: '3.8'

# mendefinisikan services yang akan digunakan
services:

  # mendefinisikan service item-app
  item-app:

    # menggunakan image dari ghcr.io
    image: ghcr.io/daudhidayatr/item-app:v1

    # melakukan expose port 8080 ke port 80
    ports:
      - 80:8080

    # menggunakan dependency ke service item-db
    depends_on:
      - item-db

    #menetapkan restart policy jika service item-app mati
    restart: always

  # mendefinisikan service item-db
  item-db:

    # menggunakan image dari mongo version 3
    image: mongo:3

    # melakukan expose port 27017 ke port 27017
    ports:
      - 27017:27017

    #menggunakan volume bernama app-db dengan target /data/db
    volumes:
      - app-db:/data/db

    # menetapkan restart policy jika service item-db mati
    restart: always

#membuat volume bernama app-db
volumes:
  app-db:


