version: '3.8'
services:
  item-app:
    image: ghcr.io/daudhidayatr/item-app:v1

    ports:
      - 80:8080

    depends_on:
      - item-db

    restart: always

  item-db:
    image: mongo:3

    ports:
      - 27017:27017

    volumes:
      - app-db:/data/db
    restart: always

volumes:
  app-db:


